# Generated by Django 5.1.1 on 2024-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0003_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
