# Generated by Django 5.1.1 on 2024-09-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0004_testimonial_image_testimonial_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_stage_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_material_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
