# Generated by Django 5.1.1 on 2024-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0007_remove_contactus_phone_contactus_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Member', max_length=100)),
                ('message', models.TextField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teammembers/')),
            ],
        ),
    ]
