# Generated by Django 5.1.1 on 2024-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0008_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
