# Generated by Django 5.1.1 on 2024-11-12 12:46

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0014_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='message',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
