# Generated by Django 5.1.1 on 2024-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0016_remove_newsletter_subject_newsletter_recipients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='recipients',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(related_name='newsletters', to='shepag_app.subscriber'),
        ),
    ]
