# Generated by Django 5.1.5 on 2025-01-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepag_app', '0020_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
